# Generated by Django 3.1 on 2020-09-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingpreference',
            name='mailchimp_subscribed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
