# Generated by Django 3.0.1 on 2020-03-23 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20200322_1643'),
        ('orders', '0002_auto_20200322_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.BillingProfile'),
        ),
    ]
